apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argo
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/bondydaa/Managing-Kubernetes-Resources-using-Helm.git
        revision: HEAD
        files:
          - path:  chapter10/multiple-envs/nginx/values/prod/values.yaml
  template:
    metadata:
      name: nginx-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/bondydaa/Managing-Kubernetes-Resources-using-Helm.git
        path: chapter10/multiple-envs/nginx
        targetRevision: HEAD
        helm:
          releaseName: nginx-dev
          valueFiles:
            - values/common-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: playground
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  syncPolicy:
    preserveResourcesOnDeletion: false
