apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argo
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/bondydaa/Managing-Kubernetes-Resources-using-Helm.git
        revision: HEAD
        files:
          - path:  playground/env/*.yaml
  template:
    metadata:
      name: nginx-{{ .path.filename | trimSuffix ".yaml" }}
    spec:
      project: default
      sources:
        - repoURL: https://github.com/bondydaa/Managing-Kubernetes-Resources-using-Helm.git
          path: chapter10/multiple-envs/nginx
          targetRevision: HEAD
          helm:
            releaseName: nginx-{{ .path.filename | trimSuffix ".yaml" }}
            valueFiles: 
              - values/common-values.yaml
            parameters:
              - name: replicaCount
                value: '{{ .replicaCount }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: playground
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  syncPolicy:
    preserveResourcesOnDeletion: false
